const { env } = process;

const AUTH_MAX_AGE_IN_SECONDS = +env.AUTH_MAX_AGE_IN_SECONDS;

const EMAIL_VERIFICATION_TIMEOUT = +env.EMAIL_VERIFICATION_TIMEOUT;
const PASSWORD_RESET_TIMEOUT = +env.PASSWORD_RESET_TIMEOUT;

module.exports = {
  AUTH_MAX_AGE_IN_SECONDS,
  EMAIL_VERIFICATION_TIMEOUT,
  PASSWORD_RESET_TIMEOUT,
};
